config/routes.rb
Rails.application.routes.draw do
  resources :baja_asignatura_registros
  resources :agregar_asignatura_registros
  resources :asignatura_registros
  resources :cambio_maestria_doctorado_registros
  resources :ampliacion_semestre_registros
  resources :baja_temporal_registros
  resources :examen_obtencion_grado_registros
  resources :solicitud_abierta_registros
  resources :segundo_director_tesis_registros
  resources :revocacion_baja_registros
  resources :cambio_comision_revisora_registros
  resources :comision_revisora_registros
  resources :cambio_comite_tutorial_registros
  resources :comite_tutorial_registros
  resources :flexibilidad_academica_registros
  resources :solicitud_programa_movilidad_registros
  resources :cursar_unidad_aprendizaje_externa_registros
  resources :cambio_tema_tesis_registros
  resources :cambio_director_tesis_registros
  resources :recursamiento_otra_unidad_registros
  resources :tema_tesis_registros
  resources :programa_posgrado_registros
  resources :director_tesis_registros
  resources :casos do
    collection do
      get 'valida_cuerpo_academico'
      get 'valida_asuntos_escolares'
      get 'valida_colegio_profesores'
      get 'cuerpo_academico'
      get 'asuntos_escolares'
      get 'colegio_profesores'
    end
  end
  resources :tipo_casos
  resources :alumnos
  devise_for :users, :controllers => { registrations: 'registrations' }
  scope "/admin" do
    resources :users
  end
  resources :users do
    collection do
      get 'panel_usuario'
      get 'panel_administrador'
      get 'panel_cuerpo_academico'
      get 'panel_asuntos_escolares'
      get 'panel_colegio_profesores'
    end
  end
  resources :tipo_usuarios
  devise_scope :user do
    root to: "devise/sessions#new"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/cambio_director_tesis_registro.rb
class CambioDirectorTesisRegistro < ApplicationRecord
  belongs_to :caso
  validates :nombre, presence:true 
end

app/controllers/cambio_director_tesis_registros_controller.rb
class CambioDirectorTesisRegistrosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_cambio_director_tesis_registro, only: [:show, :edit, :update, :destroy]

  # GET /cambio_director_tesis_registros
  # GET /cambio_director_tesis_registros.json
  def index
    @cambio_director_tesis_registros = CambioDirectorTesisRegistro.all
    authorize @cambio_director_tesis_registros
  end

  # GET /cambio_director_tesis_registros/1
  # GET /cambio_director_tesis_registros/1.json
  def show
    @cambio_director_tesis_registro = authorize CambioDirectorTesisRegistro.find(params[:id])
  end

  # GET /cambio_director_tesis_registros/new
  def new
    @cambio_director_tesis_registro = CambioDirectorTesisRegistro.new
    authorize @cambio_director_tesis_registro
  end

  # GET /cambio_director_tesis_registros/1/edit
  def edit
    @cambio_director_tesis_registro = authorize CambioDirectorTesisRegistro.find(params[:id])
  end

  # POST /cambio_director_tesis_registros
  # POST /cambio_director_tesis_registros.json
  def create
    @cambio_director_tesis_registro = CambioDirectorTesisRegistro.new(cambio_director_tesis_registro_params)
    authorize @cambio_director_tesis_registro

    respond_to do |format|
      if @cambio_director_tesis_registro.save
        format.html { redirect_to @cambio_director_tesis_registro, notice: 'La petición se guardó correctamente.' }
        format.json { render :show, status: :created, location: @cambio_director_tesis_registro }
      else
        format.html { render :new }
        format.json { render json: @cambio_director_tesis_registro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cambio_director_tesis_registros/1
  # PATCH/PUT /cambio_director_tesis_registros/1.json
  def update
    @cambio_director_tesis_registro = CambioDirectorTesisRegistro.find(params[:id])
    authorize @cambio_director_tesis_registro

    respond_to do |format|
      if @cambio_director_tesis_registro.update(cambio_director_tesis_registro_params)
        format.html { redirect_to @cambio_director_tesis_registro, notice: 'La petición se actualizó correctamente.' }
        format.json { render :show, status: :ok, location: @cambio_director_tesis_registro }
      else
        format.html { render :edit }
        format.json { render json: @cambio_director_tesis_registro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cambio_director_tesis_registros/1
  # DELETE /cambio_director_tesis_registros/1.json
  def destroy
    @cambio_director_tesis_registro = CambioDirectorTesisRegistro.find(params[:id])
    authorize @cambio_director_tesis_registro
    
    @cambio_director_tesis_registro.destroy
    respond_to do |format|
      format.html { redirect_to cambio_director_tesis_registros_url, notice: 'La petición se eliminó correctamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cambio_director_tesis_registro
      @cambio_director_tesis_registro = CambioDirectorTesisRegistro.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cambio_director_tesis_registro_params
      params.require(:cambio_director_tesis_registro).permit(:nombre, :nombre_segundo_director, :caso_id)
    end
end

app/helpers/cambio_director_tesis_registros_helper.rb
module CambioDirectorTesisRegistrosHelper
end

app/views/cambio_director_tesis_registros/_form.html.erb
<%= form_with(model: cambio_director_tesis_registro, local: true) do |form| %>
  <% if cambio_director_tesis_registro.errors.any? %>
    <div id="error_explanation">
      <h2>Los siguientes errores no permitieron que este registro se guardara:</h2>

      <ul>
        <% cambio_director_tesis_registro.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :nombre_segundo_director %>
    <%= form.text_field :nombre_segundo_director %>
  </div>

  <div class="field">
    <%= form.label :caso_id %>
    <%= form.text_field :caso_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cambio_director_tesis_registros/edit.html.erb
<h1>Editing Cambio Director Tesis Registro</h1>

<%= render 'form', cambio_director_tesis_registro: @cambio_director_tesis_registro %>

<%= link_to 'Mostrar', @cambio_director_tesis_registro %> |
<%= link_to 'Regresar', cambio_director_tesis_registros_path %>

app/views/cambio_director_tesis_registros/index.html.erb
<h1>Cambio Director Tesis Registros</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Nombre segundo director</th>
      <th>Caso</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cambio_director_tesis_registros.each do |cambio_director_tesis_registro| %>
      <tr>
        <td><%= cambio_director_tesis_registro.nombre %></td>
        <td><%= cambio_director_tesis_registro.nombre_segundo_director %></td>
        <td><%= cambio_director_tesis_registro.caso_id %></td>
        <td><%= link_to 'Mostrar', cambio_director_tesis_registro %></td>
        <td><%= link_to 'Editar', edit_cambio_director_tesis_registro_path(cambio_director_tesis_registro) %></td>
        <td><%= link_to 'Eliminar', cambio_director_tesis_registro, method: :delete, data: { confirm: '¿Está seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Cambio Director Tesis Registro', new_cambio_director_tesis_registro_path %>

app/views/cambio_director_tesis_registros/new.html.erb
<h1>New Cambio Director Tesis Registro</h1>

<%= render 'form', cambio_director_tesis_registro: @cambio_director_tesis_registro %>

<%= link_to 'Regresar', cambio_director_tesis_registros_path %>

app/views/cambio_director_tesis_registros/show.html.erb
<p>
  <strong>Nombre:</strong>
  <%= @cambio_director_tesis_registro.nombre %>
</p>

<p>
  <strong>Nombre segundo director:</strong>
  <%= @cambio_director_tesis_registro.nombre_segundo_director %>
</p>

<p>
  <strong>Caso:</strong>
  <%= @cambio_director_tesis_registro.caso_id %>
</p>

<%= link_to 'Editar', edit_cambio_director_tesis_registro_path(@cambio_director_tesis_registro) %> |
<%= link_to 'Regresar', cambio_director_tesis_registros_path %>