config/routes.rb
Rails.application.routes.draw do
  resources :baja_asignatura_registros
  resources :agregar_asignatura_registros
  resources :asignatura_registros
  resources :cambio_maestria_doctorado_registros
  resources :ampliacion_semestre_registros
  resources :baja_temporal_registros
  resources :examen_obtencion_grado_registros
  resources :solicitud_abierta_registros
  resources :segundo_director_tesis_registros
  resources :revocacion_baja_registros
  resources :cambio_comision_revisora_registros
  resources :comision_revisora_registros
  resources :cambio_comite_tutorial_registros
  resources :comite_tutorial_registros
  resources :flexibilidad_academica_registros
  resources :solicitud_programa_movilidad_registros
  resources :cursar_unidad_aprendizaje_externa_registros
  resources :cambio_tema_tesis_registros
  resources :cambio_director_tesis_registros
  resources :recursamiento_otra_unidad_registros
  resources :tema_tesis_registros
  resources :programa_posgrado_registros
  resources :director_tesis_registros
  resources :casos do
    collection do
      get 'valida_cuerpo_academico'
      get 'valida_asuntos_escolares'
      get 'valida_colegio_profesores'
      get 'cuerpo_academico'
      get 'asuntos_escolares'
      get 'colegio_profesores'
    end
  end
  resources :tipo_casos
  resources :alumnos
  devise_for :users, :controllers => { registrations: 'registrations' }
  scope "/admin" do
    resources :users
  end
  resources :users do
    collection do
      get 'panel_usuario'
      get 'panel_administrador'
      get 'panel_cuerpo_academico'
      get 'panel_asuntos_escolares'
      get 'panel_colegio_profesores'
    end
  end
  resources :tipo_usuarios
  devise_scope :user do
    root to: "devise/sessions#new"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/programa_posgrado_registro.rb
class ProgramaPosgradoRegistro < ApplicationRecord
  has_many :asignatura_registros
  has_many :alumnos
end

app/controllers/programa_posgrado_registros_controller.rb
class ProgramaPosgradoRegistrosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_programa_posgrado_registro, only: [:show, :edit, :update, :destroy]

  # GET /programa_posgrado_registros
  # GET /programa_posgrado_registros.json
  def index
    @programa_posgrado_registros = ProgramaPosgradoRegistro.all
    authorize @programa_posgrado_registros
  end

  # GET /programa_posgrado_registros/1
  # GET /programa_posgrado_registros/1.json
  def show
    @programa_posgrado_registro = authorize ProgramaPosgradoRegistro.find(params[:id])
  end

  # GET /programa_posgrado_registros/new
  def new
    @programa_posgrado_registro = ProgramaPosgradoRegistro.new
    authorize @programa_posgrado_registro
  end

  # GET /programa_posgrado_registros/1/edit
  def edit
    @programa_posgrado_registro = authorize ProgramaPosgradoRegistro.find(params[:id])
  end

  # POST /programa_posgrado_registros
  # POST /programa_posgrado_registros.json
  def create
    @programa_posgrado_registro = ProgramaPosgradoRegistro.new(programa_posgrado_registro_params)
    authorize @programa_posgrado_registro

    respond_to do |format|
      if @programa_posgrado_registro.save
        format.html { redirect_to @programa_posgrado_registro, notice: 'La petición se guardó correctamente.' }
        format.json { render :show, status: :created, location: @programa_posgrado_registro }
      else
        format.html { render :new }
        format.json { render json: @programa_posgrado_registro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /programa_posgrado_registros/1
  # PATCH/PUT /programa_posgrado_registros/1.json
  def update
    @programa_posgrado_registro = ProgramaPosgradoRegistro.find(params[:id])
    authorize @programa_posgrado_registro

    respond_to do |format|
      if @programa_posgrado_registro.update(programa_posgrado_registro_params)
        format.html { redirect_to @programa_posgrado_registro, notice: 'La petición se actualizó correctamente.' }
        format.json { render :show, status: :ok, location: @programa_posgrado_registro }
      else
        format.html { render :edit }
        format.json { render json: @programa_posgrado_registro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programa_posgrado_registros/1
  # DELETE /programa_posgrado_registros/1.json
  def destroy
    @programa_posgrado_registro = ProgramaPosgradoRegistro.find(params[:id])
    authorize @programa_posgrado_registro
    
    @programa_posgrado_registro.destroy
    respond_to do |format|
      format.html { redirect_to programa_posgrado_registros_url, notice: 'La petición se eliminó correctamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_programa_posgrado_registro
      @programa_posgrado_registro = ProgramaPosgradoRegistro.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def programa_posgrado_registro_params
      params.require(:programa_posgrado_registro).permit(:nombre)
    end
end

app/helpers/programa_posgrado_registros_helper.rb
module ProgramaPosgradoRegistrosHelper
end

app/views/programa_posgrado_registros/_form.html.erb
<%= form_with(model: programa_posgrado_registro, local: true) do |form| %>
  <% if programa_posgrado_registro.errors.any? %>
    <div id="error_explanation">
      <h2>Los siguientes errores no permitieron que este registro se guardara:</h2>

      <ul>
        <% programa_posgrado_registro.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/programa_posgrado_registros/edit.html.erb
<h1>Editing Programa Posgrado Registro</h1>

<%= render 'form', programa_posgrado_registro: @programa_posgrado_registro %>

<%= link_to 'Mostrar', @programa_posgrado_registro %> |
<%= link_to 'Regresar', programa_posgrado_registros_path %>

app/views/programa_posgrado_registros/index.html.erb
<h1>Programa Posgrado Registros</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @programa_posgrado_registros.each do |programa_posgrado_registro| %>
      <tr>
        <td><%= programa_posgrado_registro.nombre %></td>
        <td><%= link_to 'Mostrar', programa_posgrado_registro %></td>
        <td><%= link_to 'Editar', edit_programa_posgrado_registro_path(programa_posgrado_registro) %></td>
        <td><%= link_to 'Eliminar', programa_posgrado_registro, method: :delete, data: { confirm: '¿Está seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Programa Posgrado Registro', new_programa_posgrado_registro_path %>

app/views/programa_posgrado_registros/new.html.erb
<h1>New Programa Posgrado Registro</h1>

<%= render 'form', programa_posgrado_registro: @programa_posgrado_registro %>

<%= link_to 'Regresar', programa_posgrado_registros_path %>

app/views/programa_posgrado_registros/show.html.erb
<p>
  <strong>Nombre:</strong>
  <%= @programa_posgrado_registro.nombre %>
</p>

<%= link_to 'Editar', edit_programa_posgrado_registro_path(@programa_posgrado_registro) %> |
<%= link_to 'Regresar', programa_posgrado_registros_path %>