config/routes.rb
Rails.application.routes.draw do
  resources :baja_asignatura_registros
  resources :agregar_asignatura_registros
  resources :asignatura_registros
  resources :cambio_maestria_doctorado_registros
  resources :ampliacion_semestre_registros
  resources :baja_temporal_registros
  resources :examen_obtencion_grado_registros
  resources :solicitud_abierta_registros
  resources :segundo_director_tesis_registros
  resources :revocacion_baja_registros
  resources :cambio_comision_revisora_registros
  resources :comision_revisora_registros
  resources :cambio_comite_tutorial_registros
  resources :comite_tutorial_registros
  resources :flexibilidad_academica_registros
  resources :solicitud_programa_movilidad_registros
  resources :cursar_unidad_aprendizaje_externa_registros
  resources :cambio_tema_tesis_registros
  resources :cambio_director_tesis_registros
  resources :recursamiento_otra_unidad_registros
  resources :tema_tesis_registros
  resources :programa_posgrado_registros
  resources :director_tesis_registros
  resources :casos do
    collection do
      get 'valida_cuerpo_academico'
      get 'valida_asuntos_escolares'
      get 'valida_colegio_profesores'
      get 'cuerpo_academico'
      get 'asuntos_escolares'
      get 'colegio_profesores'
    end
  end
  resources :tipo_casos
  resources :alumnos
  devise_for :users, :controllers => { registrations: 'registrations' }
  scope "/admin" do
    resources :users
  end
  resources :users do
    collection do
      get 'panel_usuario'
      get 'panel_administrador'
      get 'panel_cuerpo_academico'
      get 'panel_asuntos_escolares'
      get 'panel_colegio_profesores'
    end
  end
  resources :tipo_usuarios
  devise_scope :user do
    root to: "devise/sessions#new"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/solicitud_abierta_registro.rb
class SolicitudAbiertaRegistro < ApplicationRecord
  belongs_to :caso
  validates :asunto, :motivacion, presence: true
end

app/controllers/solicitud_abierta_registros_controller.rb
class SolicitudAbiertaRegistrosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_solicitud_abierta_registro, only: [:show, :edit, :update, :destroy]

  # GET /solicitud_abierta_registros
  # GET /solicitud_abierta_registros.json
  def index
    @solicitud_abierta_registros = SolicitudAbiertaRegistro.all
    authorize @solicitud_abierta_registros
  end

  # GET /solicitud_abierta_registros/1
  # GET /solicitud_abierta_registros/1.json
  def show
    @solicitud_abierta_registro = authorize SolicitudAbiertaRegistro.find(params[:id])
  end

  # GET /solicitud_abierta_registros/new
  def new
    @solicitud_abierta_registro = SolicitudAbiertaRegistro.new
    authorize @solicitud_abierta_registro
  end

  # GET /solicitud_abierta_registros/1/edit
  def edit
    @solicitud_abierta_registro = authorize SolicitudAbiertaRegistro.find(params[:id])
  end

  # POST /solicitud_abierta_registros
  # POST /solicitud_abierta_registros.json
  def create
    @solicitud_abierta_registro = SolicitudAbiertaRegistro.new(solicitud_abierta_registro_params)
    authorize @solicitud_abierta_registro

    respond_to do |format|
      if @solicitud_abierta_registro.save
        format.html { redirect_to @solicitud_abierta_registro, notice: 'La petición se guardó correctamente.' }
        format.json { render :show, status: :created, location: @solicitud_abierta_registro }
      else
        format.html { render :new }
        format.json { render json: @solicitud_abierta_registro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /solicitud_abierta_registros/1
  # PATCH/PUT /solicitud_abierta_registros/1.json
  def update
    @solicitud_abierta_registro = SolicitudAbiertaRegistro.find(params[:id])
    authorize @solicitud_abierta_registro

    respond_to do |format|
      if @solicitud_abierta_registro.update(solicitud_abierta_registro_params)
        format.html { redirect_to @solicitud_abierta_registro, notice: 'La petición se actualizó correctamente.' }
        format.json { render :show, status: :ok, location: @solicitud_abierta_registro }
      else
        format.html { render :edit }
        format.json { render json: @solicitud_abierta_registro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /solicitud_abierta_registros/1
  # DELETE /solicitud_abierta_registros/1.json
  def destroy
    @solicitud_abierta_registro = SolicitudAbiertaRegistro.find(params[:id])
    authorize @solicitud_abierta_registro
    
    @solicitud_abierta_registro.destroy
    respond_to do |format|
      format.html { redirect_to solicitud_abierta_registros_url, notice: 'La petición se eliminó correctamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_solicitud_abierta_registro
      @solicitud_abierta_registro = SolicitudAbiertaRegistro.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def solicitud_abierta_registro_params
      params.require(:solicitud_abierta_registro).permit(:asunto, :motivacion, :caso_id)
    end
end

app/helpers/solicitud_abierta_registros_helper.rb
module SolicitudAbiertaRegistrosHelper
end

app/views/solicitud_abierta_registros/_form.html.erb
<%= form_with(model: solicitud_abierta_registro, local: true) do |form| %>
  <% if solicitud_abierta_registro.errors.any? %>
    <div id="error_explanation">
      <h2>Los siguientes errores no permitieron que este registro se guardara:</h2>

      <ul>
        <% solicitud_abierta_registro.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :asunto %>
    <%= form.text_field :asunto %>
  </div>

  <div class="field">
    <%= form.label :motivacion %>
    <%= form.text_area :motivacion %>
  </div>

  <div class="field">
    <%= form.label :caso_id %>
    <%= form.text_field :caso_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/solicitud_abierta_registros/edit.html.erb
<h1>Editing Solicitud Abierta Registro</h1>

<%= render 'form', solicitud_abierta_registro: @solicitud_abierta_registro %>

<%= link_to 'Mostrar', @solicitud_abierta_registro %> |
<%= link_to 'Regresar', solicitud_abierta_registros_path %>

app/views/solicitud_abierta_registros/index.html.erb
<h1>Solicitud Abierta Registros</h1>

<table>
  <thead>
    <tr>
      <th>Asunto</th>
      <th>Motivacion</th>
      <th>Caso</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @solicitud_abierta_registros.each do |solicitud_abierta_registro| %>
      <tr>
        <td><%= solicitud_abierta_registro.asunto %></td>
        <td><%= solicitud_abierta_registro.motivacion %></td>
        <td><%= solicitud_abierta_registro.caso_id %></td>
        <td><%= link_to 'Mostrar', solicitud_abierta_registro %></td>
        <td><%= link_to 'Editar', edit_solicitud_abierta_registro_path(solicitud_abierta_registro) %></td>
        <td><%= link_to 'Eliminar', solicitud_abierta_registro, method: :delete, data: { confirm: '¿Está seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Solicitud Abierta Registro', new_solicitud_abierta_registro_path %>

app/views/solicitud_abierta_registros/new.html.erb
<h1>New Solicitud Abierta Registro</h1>

<%= render 'form', solicitud_abierta_registro: @solicitud_abierta_registro %>

<%= link_to 'Regresar', solicitud_abierta_registros_path %>

app/views/solicitud_abierta_registros/show.html.erb
<p>
  <strong>Asunto:</strong>
  <%= @solicitud_abierta_registro.asunto %>
</p>

<p>
  <strong>Motivacion:</strong>
  <%= @solicitud_abierta_registro.motivacion %>
</p>

<p>
  <strong>Caso:</strong>
  <%= @solicitud_abierta_registro.caso_id %>
</p>

<%= link_to 'Editar', edit_solicitud_abierta_registro_path(@solicitud_abierta_registro) %> |
<%= link_to 'Regresar', solicitud_abierta_registros_path %>