config/routes.rb
Rails.application.routes.draw do
  resources :baja_asignatura_registros
  resources :agregar_asignatura_registros
  resources :asignatura_registros
  resources :cambio_maestria_doctorado_registros
  resources :ampliacion_semestre_registros
  resources :baja_temporal_registros
  resources :examen_obtencion_grado_registros
  resources :solicitud_abierta_registros
  resources :segundo_director_tesis_registros
  resources :revocacion_baja_registros
  resources :cambio_comision_revisora_registros
  resources :comision_revisora_registros
  resources :cambio_comite_tutorial_registros
  resources :comite_tutorial_registros
  resources :flexibilidad_academica_registros
  resources :solicitud_programa_movilidad_registros
  resources :cursar_unidad_aprendizaje_externa_registros
  resources :cambio_tema_tesis_registros
  resources :cambio_director_tesis_registros
  resources :recursamiento_otra_unidad_registros
  resources :tema_tesis_registros
  resources :programa_posgrado_registros
  resources :director_tesis_registros
  resources :casos do
    collection do
      get 'valida_cuerpo_academico'
      get 'valida_asuntos_escolares'
      get 'valida_colegio_profesores'
      get 'cuerpo_academico'
      get 'asuntos_escolares'
      get 'colegio_profesores'
    end
  end
  resources :tipo_casos
  resources :alumnos
  devise_for :users, :controllers => { registrations: 'registrations' }
  scope "/admin" do
    resources :users
  end
  resources :users do
    collection do
      get 'panel_usuario'
      get 'panel_administrador'
      get 'panel_cuerpo_academico'
      get 'panel_asuntos_escolares'
      get 'panel_colegio_profesores'
    end
  end
  resources :tipo_usuarios
  devise_scope :user do
    root to: "devise/sessions#new"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/alumno.rb
class Alumno < ApplicationRecord
  belongs_to :user
  has_many :casos, dependent: :destroy
  belongs_to :programa_posgrado_registro
  validates :cvu, presence:true
end

app/models/caso.rb
class Caso < ApplicationRecord
  belongs_to :alumno
  belongs_to :tipo_caso
  has_many :director_tesis_registros, dependent: :destroy
  has_many :tema_tesis_registros, dependent: :destroy
  has_many :recursamiento_otra_unidad_registros, dependent: :destroy
  has_many :cambio_director_tesis_registros, dependent: :destroy
  has_many :cambio_tema_tesis_registros, dependent: :destroy
  has_many :cursar_unidad_aprendizaje_externa_registros, dependent: :destroy
  has_many :solicitud_programa_movilidad_registros, dependent: :destroy
  has_many :flexibilidad_academica_registros, dependent: :destroy
  has_many :comite_tutorial_registros, dependent: :destroy
  has_many :cambio_comite_tutorial_registros, dependent: :destroy
  has_many :comision_revisora_registros, dependent: :destroy
  has_many :cambio_comision_revisora_registros, dependent: :destroy
  has_many :revocacion_baja_registros, dependent: :destroy
  has_many :segundo_director_tesis_registros, dependent: :destroy
  has_many :solicitud_abierta_registros, dependent: :destroy
  has_many :examen_obtencion_grado_registros, dependent: :destroy
  has_many :baja_temporal_registros, dependent: :destroy
  has_many :ampliacion_semestre_registros, dependent: :destroy
  has_many :cambio_maestria_doctorado_registros, dependent: :destroy
  has_many :agregar_asignatura_registros, dependent: :destroy
  has_many :baja_asignatura_registros, dependent: :destroy

  accepts_nested_attributes_for :director_tesis_registros, :tema_tesis_registros,
  :recursamiento_otra_unidad_registros, :cambio_director_tesis_registros,
  :cambio_tema_tesis_registros, :cursar_unidad_aprendizaje_externa_registros,
  :solicitud_programa_movilidad_registros, :flexibilidad_academica_registros,
  :comite_tutorial_registros, :cambio_comite_tutorial_registros,
  :comision_revisora_registros, :cambio_comision_revisora_registros,
  :revocacion_baja_registros, :segundo_director_tesis_registros,
  :solicitud_abierta_registros, :examen_obtencion_grado_registros,
  :baja_temporal_registros, :ampliacion_semestre_registros,
  :cambio_maestria_doctorado_registros, :agregar_asignatura_registros,
  :baja_asignatura_registros

  def self.validacion_cuerpo_academico(caso_ids)
    casos = Caso.find(caso_ids)
    casos.each do |caso|
      caso.update_attributes(validacion_cuerpo_academico: true)
    end
  end

  def self.validacion_asuntos_escolares(caso_ids)
    casos = Caso.find(caso_ids)
    casos.each do |caso|
      caso.update_attributes(validacion_asuntos_escolares: true)
    end
  end

  def self.validacion_colegio_profesores(caso_ids)
    casos = Caso.find(caso_ids)
    casos.each do |caso|
      caso.update_attributes(validacion_colegio_profesores: true)
    end
  end

end

app/controllers/casos_controller.rb
class CasosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_caso, only: [:show, :edit, :update, :destroy]

  # GET /casos
  # GET /casos.json
  def index
    @casos = Caso.all
    authorize @casos
  end

  # GET /casos/1
  # GET /casos/1.json
  def show
    @caso = authorize Caso.find(params[:id])
  end

  # GET /casos/new
  def new
    alumno = Alumno.find_by(user_id: current_user.id)
    @alumno_actual = alumno
    @caso = alumno.casos.build
    @caso.director_tesis_registros.build
    @caso.tema_tesis_registros.build
    @caso.recursamiento_otra_unidad_registros.build
    @caso.cambio_director_tesis_registros.build
    @caso.cambio_tema_tesis_registros.build
    @caso.cursar_unidad_aprendizaje_externa_registros.build
    @caso.solicitud_programa_movilidad_registros.build
    @caso.flexibilidad_academica_registros.build
    @caso.comite_tutorial_registros.build
    @caso.cambio_comite_tutorial_registros.build
    @caso.comision_revisora_registros.build
    @caso.cambio_comision_revisora_registros.build
    @caso.revocacion_baja_registros.build
    @caso.segundo_director_tesis_registros.build
    @caso.solicitud_abierta_registros.build
    @caso.examen_obtencion_grado_registros.build
    @caso.baja_temporal_registros.build
    @caso.ampliacion_semestre_registros.build
    @caso.cambio_maestria_doctorado_registros.build
    @caso.agregar_asignatura_registros.build
    @caso.baja_asignatura_registros.build
  end

  # GET /casos/1/edit
  def edit
    @caso = authorize Caso.find(params[:id])
  end

  # POST /casos
  # POST /casos.json
  def create
    alumno = Alumno.find_by(user_id: current_user.id)
    @caso = alumno.casos.build(caso_params)
    authorize @caso

    respond_to do |format|
      if @caso.save
        format.html { redirect_to panel_usuario_users_path, notice: 'La petición se guardó correctamente.' }
        format.json { render :show, status: :created, location: @caso }
      else
        format.html { render :new }
        format.json { render json: @caso.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /casos/1
  # PATCH/PUT /casos/1.json
  def update
    @caso = Caso.find(params[:id])
    authorize @caso

    respond_to do |format|
      if @caso.update(caso_params)
        format.html { redirect_to @caso, notice: 'La petición se actualizó correctamente.' }
        format.json { render :show, status: :ok, location: @caso }
      else
        format.html { render :edit }
        format.json { render json: @caso.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /casos/1
  # DELETE /casos/1.json
  def destroy
    @caso = Caso.find(params[:id])
    authorize @caso

    @caso.destroy
    respond_to do |format|
      format.html { redirect_to casos_url, notice: 'La petición se eliminó correctamente.' }
      format.json { head :no_content }
    end
  end

  def cuerpo_academico
    @casos = Caso.all
    authorize @casos
  end

  def asuntos_escolares
    @casos = Caso.all
    authorize @casos
  end

  def colegio_profesores
    @casos = Caso.all
    authorize @casos
  end

  def valida_cuerpo_academico
    @casos = Caso.validacion_cuerpo_academico(params[:caso_ids])
    redirect_to cuerpo_academico_casos_path, notice: 'Los casos han sido validados correctamente.'
  end

  def valida_asuntos_escolares
    @casos = Caso.validacion_asuntos_escolares(params[:caso_ids])
    redirect_to asuntos_escolares_casos_path, notice: 'Los casos han sido validados correctamente.'
  end

  def valida_colegio_profesores
    @casos = Caso.validacion_colegio_profesores(params[:caso_ids])
    redirect_to colegio_profesores_casos_path, notice: 'Los casos han sido validados correctamente.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_caso
      @caso = Caso.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def caso_params
      params.require(:caso).permit(:alumno_id, :tipo_caso_id, :validacion_cuerpo_academico, :validacion_asuntos_escolares, :validacion_colegio_profesores,
         director_tesis_registros_attributes: [:id, :nombre, :nombre_segundo_director, :caso_id],
         tema_tesis_registros_attributes: [:id, :nombre, :caso_id],
         recursamiento_otra_unidad_registros_attributes: [:id, :nombre, :clave, :creditos, :nombre_unidad_academica, :caso_id],
         cambio_director_tesis_registros_attributes: [:id, :nombre, :nombre_segundo_director, :caso_id],
         cambio_tema_tesis_registros_attributes: [:id, :nombre, :caso_id],
         cursar_unidad_aprendizaje_externa_registros_attributes: [:id, :nombre, :clave, :creditos, :unidad_academica, :caso_id],
         solicitud_programa_movilidad_registros_attributes: [:id, :nombre, :nombre_institucion, :caso_id],
         flexibilidad_academica_registros_attributes: [:id, :nombre, :caso_id],
         comite_tutorial_registros_attributes: [:id, :primer_tutor, :segundo_tutor, :tercer_tutor, :cuarto_tutor, :quinto_tutor, :caso_id],
         cambio_comite_tutorial_registros_attributes: [:id, :primer_tutor, :segundo_tutor, :tercer_tutor, :cuarto_tutor, :quinto_tutor, :caso_id],
         comision_revisora_registros_attributes: [:id, :presidente, :secretario, :primer_vocal, :segundo_vocal, :tercer_vocal, :suplente, :caso_id],
         cambio_comision_revisora_registros_attributes: [:id, :presidente, :secretario, :primer_vocal, :segundo_vocal, :tercer_vocal, :suplente, :caso_id],
         revocacion_baja_registros_attributes: [:id, :motivacion, :caso_id],
         segundo_director_tesis_registros_attributes: [:id, :nombre, :caso_id],
         solicitud_abierta_registros_attributes: [:id, :asunto, :motivacion, :caso_id],
         examen_obtencion_grado_registros_attributes: [:id, :motivacion, :caso_id],
         baja_temporal_registros_attributes: [:id, :motivacion, :caso_id],
         ampliacion_semestre_registros_attributes: [:id, :motivacion, :caso_id],
         cambio_maestria_doctorado_registros_attributes: [:id, :motivacion, :caso_id],
         agregar_asignatura_registros_attributes: [:id, :asignatura_registro_id, :caso_id],
         baja_asignatura_registros_attributes: [:id, :asignatura_registro_id, :caso_id])
    end
end

app/helpers/casos_helper.rb
module CasosHelper
end

app/views/casos/_baja_temporal_registro.html.erb
<%= form.fields_for :baja_temporal_registros do |baja_temporal_registros_form| %>
  <div class="form-group col-sm-10">
    <%= baja_temporal_registros_form.label :motivacion, 'Escriba por favor el fundamento o motivacion de la petición' %>
    <%= baja_temporal_registros_form.text_area :motivacion, class: 'form-control', minlength: '20', :required => true %>
  </div>
<% end %>

app/views/casos/_cambio_comision_revisora_registro.html.erb
<%= form.fields_for :cambio_comision_revisora_registros do |cambio_comision_revisora_registros_form| %>
  <div class="form-group col-sm-3">
    <%= cambio_comision_revisora_registros_form.label :presidente, 'Presidente' %>
    <%= cambio_comision_revisora_registros_form.text_field :presidente, class: 'form-control', :required => true %>
  </div>
  <div class="form-group col-sm-3">
    <%= cambio_comision_revisora_registros_form.label :secretario, 'Secretario' %>
    <%= cambio_comision_revisora_registros_form.text_field :secretario, class: 'form-control', :required => true %>
  </div>
  <div class="form-group col-sm-3">
    <%= cambio_comision_revisora_registros_form.label :primer_vocal, 'Primer vocal' %>
    <%= cambio_comision_revisora_registros_form.text_field :primer_vocal, class: 'form-control', :required => true %>
  </div>
  <div class="form-group col-sm-3">
    <%= cambio_comision_revisora_registros_form.label :segundo_vocal, 'Segundo vocal' %>
    <%= cambio_comision_revisora_registros_form.text_field :segundo_vocal, class: 'form-control', :required => true %>
  </div>
  <div class="form-group col-sm-3">
    <%= cambio_comision_revisora_registros_form.label :tercer_vocal, 'Tercer vocal' %>
    <%= cambio_comision_revisora_registros_form.text_field :tercer_vocal, class: 'form-control', :required => true %>
  </div>
  <div class="form-group col-sm-3">
    <%= cambio_comision_revisora_registros_form.label :suplente, 'Suplente' %>
    <%= cambio_comision_revisora_registros_form.text_field :suplente, class: 'form-control', :required => true %>
  </div>
<% end %>

app/views/casos/_cambio_comite_tutorial_registro.html.erb
<%= form.fields_for :cambio_comite_tutorial_registros do |cambio_comite_tutorial_registros_form| %>
  <div class="form-group col-sm-3">
    <%= cambio_comite_tutorial_registros_form.label :primer_tutor, 'Primer tutor' %>
    <%= cambio_comite_tutorial_registros_form.text_field :primer_tutor, class: 'form-control', :required => true %>
  </div>
  <div class="form-group col-sm-3">
    <%= cambio_comite_tutorial_registros_form.label :segundo_tutor, 'Segundo tutor' %>
    <%= cambio_comite_tutorial_registros_form.text_field :segundo_tutor, class: 'form-control', :required => true %>
  </div>
  <div class="form-group col-sm-3">
    <%= cambio_comite_tutorial_registros_form.label :tercer_tutor, 'Tercer tutor' %>
    <%= cambio_comite_tutorial_registros_form.text_field :tercer_tutor, class: 'form-control', :required => true%>
  </div>
  <div class="form-group col-sm-3">
    <%= cambio_comite_tutorial_registros_form.label :cuarto_tutor, 'Cuarto tutor' %>
    <%= cambio_comite_tutorial_registros_form.text_field :cuarto_tutor, class: 'form-control', :required => true %>
  </div>
  <div class="form-group col-sm-3">
    <%= cambio_comite_tutorial_registros_form.label :quinto_tutor, 'Quinto tutor' %>
    <%= cambio_comite_tutorial_registros_form.text_field :quinto_tutor, class: 'form-control', :required => true %>
  </div>
<% end %>

app/views/casos/_cambio_tema_tesis_registro.html.erb
<%= form.fields_for :cambio_tema_tesis_registros do |cambio_tema_tesis_registros_form| %>
  <div class="form-group col-sm-3">
    <%= cambio_tema_tesis_registros_form.label :nombre, 'Nuevo tema de tesis' %>
    <%= cambio_tema_tesis_registros_form.text_field :nombre, class: 'form-control', :required => true  %>
  </div>
<% end %>

app/views/casos/_comision_revisora_registro.html.erb
<%= form.fields_for :comision_revisora_registros do |comision_revisora_registros_form| %>
  <div class="form-group col-sm-3">
    <%= comision_revisora_registros_form.label :presidente, 'Presidente' %>
    <%= comision_revisora_registros_form.text_field :presidente, class: 'form-control', :required => true %>
  </div>
  <div class="form-group col-sm-3">
    <%= comision_revisora_registros_form.label :secretario, 'Secretario' %>
    <%= comision_revisora_registros_form.text_field :secretario, class: 'form-control', :required => true %>
  </div>
  <div class="form-group col-sm-3">
    <%= comision_revisora_registros_form.label :primer_vocal, 'Primer vocal' %>
    <%= comision_revisora_registros_form.text_field :primer_vocal, class: 'form-control', :required => true %>
  </div>
  <div class="form-group col-sm-3">
    <%= comision_revisora_registros_form.label :segundo_vocal, 'Segundo vocal' %>
    <%= comision_revisora_registros_form.text_field :segundo_vocal, class: 'form-control', :required => true %>
  </div>
  <div class="form-group col-sm-3">
    <%= comision_revisora_registros_form.label :tercer_vocal, 'Tercer vocal' %>
    <%= comision_revisora_registros_form.text_field :tercer_vocal, class: 'form-control', :required => true %>
  </div>
  <div class="form-group col-sm-3">
    <%= comision_revisora_registros_form.label :suplente, 'Suplente' %>
    <%= comision_revisora_registros_form.text_field :suplente, class: 'form-control', :required => true %>
  </div>
<% end %>

app/views/casos/_cursar_unidad_aprendizaje_externa_registro.html.erb
<%= form.fields_for :cursar_unidad_aprendizaje_externa_registros do |cursar_unidad_aprendizaje_externa_registros_form| %>
  <div class="form-group col-sm-3">
    <%= cursar_unidad_aprendizaje_externa_registros_form.label :nombre, 'Nombre de la unidad de aprendizaje' %>
    <%= cursar_unidad_aprendizaje_externa_registros_form.text_field :nombre, class: 'form-control', :required => true %>
  </div>
  <div class="form-group col-sm-3">
    <%= cursar_unidad_aprendizaje_externa_registros_form.label :clave, 'Clave de la unidad de aprendizaje' %>
    <%= cursar_unidad_aprendizaje_externa_registros_form.text_field :clave, class: 'form-control', :required => true  %>
  </div>
  <div class="form-group col-sm-3">
    <%= cursar_unidad_aprendizaje_externa_registros_form.label :creditos, 'Créditos de la unidad de aprendizaje' %>
    <%= cursar_unidad_aprendizaje_externa_registros_form.text_field :creditos, class: 'form-control', :required => true %>
  </div>
  <div class="form-group col-sm-3">
    <%= cursar_unidad_aprendizaje_externa_registros_form.label :unidad_academica, 'Nombre de la unidad académica' %>
    <%= cursar_unidad_aprendizaje_externa_registros_form.text_field :unidad_academica, class: 'form-control', :required => true  %>
  </div>
<% end %>

app/views/casos/_examen_obtencion_grado_registro.html.erb
<%= form.fields_for :examen_obtencion_grado_registros do |examen_obtencion_grado_registros_form| %>
  <div class="form-group col-sm-10">
    <%= examen_obtencion_grado_registros_form.label :motivacion, 'Escriba por favor el fundamento o motivacion de la petición' %>
    <%= examen_obtencion_grado_registros_form.text_area :motivacion, class: 'form-control', minlength: '20', :required => true%>
  </div>
<% end %>

app/views/casos/_form.html.erb
<%= form_with(model: caso, local: true) do |form| %>
  <% if caso.errors.any? %>
    <div id="error_explanation">
      <h2>Los siguientes errores no permitieron que este registro se guardara:</h2>

      <ul>
        <% caso.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="form-group col-sm-4">
      <%= form.label :tipo_caso_id, 'Tipo de caso' %>
      <%= collection_select(:caso, :tipo_caso_id, TipoCaso.all.order(nombre: :asc), :id, :nombre, {prompt: 'Seleccione'}, class: 'form-control') %>
    </div>
  </div>

  <div class="row resultado"></div>

  <div class="row">
    <div class="actions col-sm-4">
      <%= form.submit "Enviar", class: "btn btn-md btn-primary" %>
    </div>
  </div>

  <script>
    const selectElement = document.querySelector('.form-control');

    selectElement.addEventListener('change', (event) => {
        const resultado = document.querySelector('.resultado');
        if (event.target.value == 1){
          resultado.innerHTML = `<%= j render partial: "casos/director_tesis_registro", locals:{form: form} %>`;
        }
        else if (event.target.value == 2){
          resultado.innerHTML = `<%= j render partial: "casos/agregar_asignatura_registro", locals:{form: form} %>`;
        }
        else if (event.target.value == 3){
          resultado.innerHTML = `<%= j render partial: "casos/tema_tesis_registro", locals:{form: form} %>`;
        }
        else if (event.target.value == 4){
          resultado.innerHTML = `<%= j render partial: "casos/recursamiento_otra_unidad_registro", locals:{form: form} %>`;
        }
        else if (event.target.value == 5){
          resultado.innerHTML = `<%= j render partial: "casos/cambio_director_tesis_registro", locals:{form: form} %>`;
        }
        else if (event.target.value == 6){
          resultado.innerHTML = `<%= j render partial: "casos/cambio_tema_tesis_registro", locals:{form: form} %>`;
        }
        else if (event.target.value == 7){
          resultado.innerHTML = `<%= j render partial: "casos/cursar_unidad_aprendizaje_externa_registro", locals:{form: form} %>`;
        }
        else if (event.target.value == 8){
          resultado.innerHTML = `<%= j render partial: "casos/solicitud_programa_movilidad_registro", locals:{form: form} %>`;
        }
        else if (event.target.value == 9){
          resultado.innerHTML = `<%= j render partial: "casos/flexibilidad_academica_registro", locals:{form: form} %>`;
        }
        else if (event.target.value == 10){
          resultado.innerHTML = `<%= j render partial: "casos/comite_tutorial_registro", locals:{form: form} %>`;
        }
        else if (event.target.value == 11){
          resultado.innerHTML = `<%= j render partial: "casos/cambio_comite_tutorial_registro", locals:{form: form} %>`;
        }
        else if (event.target.value == 12){
          resultado.innerHTML = `<%= j render partial: "casos/comision_revisora_registro", locals:{form: form} %>`;
        }
        else if (event.target.value == 13){
          resultado.innerHTML = `<%= j render partial: "casos/cambio_comision_revisora_registro", locals:{form: form} %>`;
        }
        else if (event.target.value == 14){
          resultado.innerHTML = `<%= j render partial: "casos/revocacion_baja_registro", locals:{form: form} %>`;
        }
        else if (event.target.value == 15){
          resultado.innerHTML = `<%= j render partial: "casos/segundo_director_tesis_registro", locals:{form: form} %>`;
        }
        else if (event.target.value == 16){
          resultado.innerHTML = `<%= j render partial: "casos/solicitud_abierta_registro", locals:{form: form} %>`;
        }
        else if (event.target.value == 17){
          resultado.innerHTML = `<%= j render partial: "casos/examen_obtencion_grado_registro", locals:{form: form} %>`;
        }
        else if (event.target.value == 18){
          resultado.innerHTML = `<%= j render partial: "casos/baja_temporal_registro", locals:{form: form} %>`;
        }
        else if (event.target.value == 19){
          resultado.innerHTML = `<%= j render partial: "casos/ampliacion_semestre_registro", locals:{form: form} %>`;
        }
        else if (event.target.value == 20){
          resultado.innerHTML = `<%= j render partial: "casos/cambio_maestria_doctorado_registro", locals:{form: form} %>`;
        }
        else if (event.target.value == 21){
          resultado.innerHTML = `<%= j render partial: "casos/baja_asignatura_registro", locals:{form: form} %>`;
        }
    });
  </script>
<% end %>

app/views/casos/_segundo_director_tesis_registro.html.erb
<%= form.fields_for :segundo_director_tesis_registros do |segundo_director_tesis_registros_form| %>
  <div class="form-group col-sm-3">
    <%= segundo_director_tesis_registros_form.label :nombre %>
    <%= segundo_director_tesis_registros_form.text_field :nombre, class: 'form-control', :required => true%>
  </div>
<% end %>

app/views/casos/colegio_profesores.html.erb
<h1>Validar casos</h1>
<%= form_tag valida_colegio_profesores_casos_path, method: :get do %>
  <table class="table table-bordered">
    <thead class="thead-light">
      <tr>
        <% if policy(@casos).valida_colegio_profesores? %>
          <th scope="col" class="sort" data-sort="name" rowspan="2"></th>
        <% end %>
        <th scope="col" class="sort" data-sort="name" rowspan="2">Nombre</th>
        <th scope="col" class="sort" data-sort="budget" rowspan="2">Primer<br>apellido</th>
        <th scope="col" class="sort" data-sort="budget" rowspan="2">Segundo<br>apellido</th>
        <th scope="col" class="sort" data-sort="budget" rowspan="2">Boleta</th>
        <th scope="col" class="sort" data-sort="budget" rowspan="2">Tipo<br>de<br>caso</th>
        <th scope="col" class="sort" data-sort="status" colspan="3" style="text-align:center;">Validación</th>
      </tr>
      <tr>
        <th>Cuerpo<br>académico</th>
        <th>Ansuntos<br>escolares</th>
        <th>Colegio<br>de<br>profesores</th>
      </tr>
    </thead>

    <tbody>
      <% @casos.each do |caso| %>
        <tr>
          <% if policy(@casos).valida_colegio_profesores? %>
            <td><%= check_box_tag "caso_ids[]", caso.id %></td>
          <% end %>
          <td><%= caso.alumno.user.nombre %></td>
          <td><%= caso.alumno.user.primer_apellido %></td>
          <td><%= caso.alumno.user.segundo_apellido %></td>
          <td><%= caso.alumno.boleta %></td>
          <td><%= caso.tipo_caso.nombre %></td>
          <td>
            <span class="badge badge-dot mr-4">
              <% if caso.validacion_cuerpo_academico == false %>
                <div class="btn-warning btn-circle btn-sm" align="center">
                  <i class="fas fa-clock"></i>
                </div>
              <% else %>
                <div class="btn-success btn-circle btn-sm" align="center">
                  <i class="fas fa-check"></i>
                </div>
              <% end %>
            </span>
          </td>
          <td>
            <span class="badge badge-dot mr-4">
              <% if caso.validacion_asuntos_escolares == false %>
                <div class="btn-warning btn-circle btn-sm" align="center">
                  <i class="fas fa-clock"></i>
                </div>
              <% else %>
              <div class="btn-success btn-circle btn-sm" align="center">
                <i class="fas fa-check"></i>
              </div>
              <% end %>
            </span>
          </td>
          <td>
            <span class="badge badge-dot mr-4">
              <% if caso.validacion_colegio_profesores == false %>
                <div class="btn-warning btn-circle btn-sm" align="center">
                  <i class="fas fa-clock"></i>
                </div>
              <% else %>
              <div class="btn-success btn-circle btn-sm" align="center">
                <i class="fas fa-check"></i>
              </div>
              <% end %>
            </span>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <% if policy(@casos).valida_colegio_profesores? %>
    <input type="checkbox" id="check_all" value="check_all"><strong> Seleccionar / Deseleccionar todos</strong><br><br>
    <%= submit_tag "validar seleccionados", class: 'btn btn-primary' %>
  <% end %>
<% end %>
<script>
  $('#check_all').on("click", function(){
    var checkboxes = $('input[type="checkbox"]');
    checkboxes.prop("checked", !checkboxes.prop("checked"));
  });
</script>

<br>

app/views/casos/edit.html.erb
<h1>Editar Caso</h1>

<%= render 'form', caso: @caso %>

<%= link_to 'Mostrar', @caso %> |
<%= link_to 'Regresar', casos_path %>

app/views/casos/show.html.erb
<p>
  <strong>User:</strong>
  <%= @caso.alumno.user.nombre %>
</p>

<p>
  <strong>Tipo caso:</strong>
  <%= @caso.tipo_caso.nombre %>
</p>

<%= link_to 'Editar', edit_caso_path(@caso) %> |
<%= link_to 'Regresar', casos_path %>